name: CD - Test and deploy

on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              mkdir /home/farm
              cd /home/farm
              git pull origin main # git clone git@github.com:koekkoek/my-project.git 
              systemctl restart --now farm
              echo "Deployment succesfull to digital ocean"
          